"""empty message

Revision ID: 96c9fcf8ecc1
Revises: b0c1e8a66c9c
Create Date: 2020-07-13 22:41:38.583778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96c9fcf8ecc1'
down_revision = 'b0c1e8a66c9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
